language: bash
sudo: required
before_script:
    - chmod +x install_mpich.sh
    - chmod +x compile.sh
    - chmod +x pushgithub.sh
    - ./install_mpich.sh
script:
    - ./compile.sh hello 5
after_success:
    - ./pushgithub.sh

